### ISSUE TITLE
下载引擎永远更新下载失败，优酷视频无法下载1080P版本

### ISSUE THREAD

**Issue by Alexanderhanks** [ingbyr/GUI-YouGet#29]
![_20171203204029](https://user-images.githubusercontent.com/34210341/33525442-894a2a4e-d86a-11e7-8a66-783c3d1e54a0.jpg)
![_20171203204059](https://user-images.githubusercontent.com/34210341/33525443-8988d08c-d86a-11e7-9b10-78f7f5479fdd.jpg)
![_20171203204238](https://user-images.githubusercontent.com/34210341/33525444-89c53b62-d86a-11e7-820c-9bc2e03a0e83.jpg)

**Comment by willpangela** [comment]
自己下个py 装个you-get能下1080p的 不要怕命令行 我文科生都搞定了

**Comment by Alexanderhanks** [comment]
我装了，但是装了这个以后，youget用不了了，我这个还得下载搜狐视频，还不能卸载

**Comment by willpangela** [comment]
没明白你的这个说的是哪个 也搞不懂卸载不卸载跟你的问题有啥关系...

**Comment by shirh19910112** [comment]
我看了一下日志，发现you-get没有0.4.995的Win版本，所以直接使用地址https://github.com/soimort/you-get/releases/download/v0.4.995/you-get-0.4.995-win32.exe进行下载就会出现错误，因为不存在该文件。故更新失败。

**Comment by willpangela** [comment]
楼上说的我明白 可问题是995出来之前990版本有EXE的时候我在gui里面更新也不成功

**Comment by shirh19910112** [comment]
的确有问题，我从https://github.com/soimort/you-get/releases/下载的0.4.985替换到core文件夹下，提示版本还是0.4.915，而且使用也是不正常的，应该是有bug。

**Comment by willpangela** [comment]
回楼上 我也替换了新版本core也不行 另外显示版本那个是根据根目录的一个配置文本来的 自己随便瞎写都行……

**Comment by Alexanderhanks** [comment]
就是这个意思，如图，我在安装GUI-youget前，是可以这么下载优酷视频的，但是现在就是这个情况
![_20171205202111](https://user-images.githubusercontent.com/34210341/33606863-fab5552e-d9f9-11e7-8caf-4f558b464f9c.png)

**Comment by yuanchongfu** [comment]
C:\Users\Administrator>you-get --format=3 http://v.pptv.com/show/HFozsRlic7y2QDnY.html?rcc_src=L1
It seems that your ffmpeg is a nightly build.
Please switch to the latest stable if merging failed.
site:                PPTV
title:               东风破(第01集)
stream:
    - format:        3
      container:     mp4
      video-profile: 1920x1080@2573kbps
      size:          836.2 MiB (876772936 bytes)
    # download-with: you-get --format=3 [URL]

Downloading 东风破(第01集).mp4 ...
 0.0% (  0.0/836.2MB) ├──────────────────────────────────────┤[ 1/41] you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

**Comment by yuanchongfu** [comment]
腾讯不能下载
C:\Users\Administrator>you-get https://v.qq.com/x/cover/n62tix4mc92a8bh.html
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.
It seems that your ffmpeg is a nightly build.
Please switch to the latest stable if merging failed.
